version: '3.3'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - wp_database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - docker_network
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wp_database:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - docker_network
    ports:
      - "9000"
    # restart: always

  nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    restart: always

volumes:
  wp_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp_database

  wp_website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp_website

networks:
  docker_network:
    driver: bridge